name: GuiShop
main: GuiShop\Main
version: 1.0.0-BETA2
api: [3.0.0, 4.0.0, 3.5.6]
author: VMPE Developement Team
description: ShopUI for servers!
priority: LOWEST
commands:
 shop:
  description: Opens the shop gui
